### PR TITLE
fix(box): add forwardRef to box component

### PR DESCRIPTION
**Pull request by capricorn-32**
**Notes for Reviewers**

This PR fixes #
Added forwardRef to all the sistent base component

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by aabidsofi19** [comment]
@capricorn-32  there are some lint failures

**Comment by capricorn-32** [comment]
@aabidsofi19 In Avatar component right or In other component ?

**Comment by Ajay-singh1** [comment]
@capricorn-32 You forgot to sign your commits!

**Comment by capricorn-32** [comment]
@Ajay-singh1 there is ton of work left and I will do that in the end.

**Comment by sudhanshutech** [comment]
@capricorn-32 
Let's discuss this during the website call on Monday at 6:30 PM IST (7:00 AM CT).

Please add it as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?tab=t.0).

**Comment by aabidsofi19** [comment]
ready to merge ?

**Comment by capricorn-32** [comment]
@aabidsofi19 Wait

**Comment by capricorn-32** [comment]
@aabidsofi19 Yes, we can merge this.

**Pull request merged**
