### PR TITLE
Remove duplicate dependencies @types/lodash

### PR DESCRIPTION
**Pull request by amitamrutiya**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by amitamrutiya** [comment]
@sudhanshutech Could you please review and merge

**Comment by leecalcote** [comment]
> @sudhanshutech Could you please review and merge this?

Nice! Good job on urging for review, @amitamrutiya

**Review by leecalcote — COMMENTED** [review]
@amitamrutiya @nebula-aac  there needs to be package-lock.json?

**Review by sudhanshutech — APPROVED** [review]

**Review by sudhanshutech — CHANGES_REQUESTED** [review]
please check the build and add package-lock file too if its been removed of `@type`

**Comment by amitamrutiya** [comment]
I removed the dependencies written twice so there is already present metadata in the package-lock.json file. So there would be no changes in the package-lock.json file and build as well.

**Review by sudhanshutech — APPROVED** [review]

**Pull request merged**
