### PR TITLE
setup prettier in workspace

### PR DESCRIPTION
**Pull request by nebula-aac**
**Notes for Reviewers**

This PR fixes #https://github.com/layer5io/sistent/issues/19

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by aabidsofi19 — COMMENTED** [review]
will this  be  run as precommit-hook and will it respect then the nested ( package specific configs)

**Comment by nebula-aac** [comment]
For now it running across all files. It did not make any changes to the `design-system`, because this prettier config is copied from that directory.

**Comment by aabidsofi19** [comment]
conficts ^^

**Comment by leecalcote** [comment]
Resolved merge conflict.

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
