### PR TITLE
Nomination of Antonette Caldwell as a maintainer of sistent

### PR DESCRIPTION
**Pull request by ritiksaxena124**
### Nomination of [Antonette Caldwell](https://layer5.io/community/members/antonette-caldwell) as a maintainer of "Sistent"
Antonette Caldwell (@nebula-aac)  is actively involved in the development of "Sistent," a comprehensive design system of Layer5. Her contributions to this project demonstrate her commitment to enhancing user experiences and visual consistency within Layer5 projects.
Antonette's dedication and expertise make her an invaluable asset to the Sistent project and the broader design community.

### CODE REVIEW

**Comment by leecalcote** [comment]
+1

**Comment by aabidsofi19** [comment]
+1 
whooo

**Comment by abhijeetgauravm** [comment]
+1

**Comment by theBeginner86** [comment]
+1

**Comment by officialarmannqureshi** [comment]
+

**Comment by Yashsharma1911** [comment]
+1 whao 🎈

**Comment by ritiksaxena124** [comment]
+1

**Comment by sudhanshutech** [comment]
+1

**Review by leecalcote — APPROVED** [review]
🎈

**Pull request merged**
