### PR TITLE
Refactor Catalog Card and add flip effect

### PR DESCRIPTION
**Pull request by sudhanshutech**
**Notes for Reviewers**

This PR fixes #
{97846736-D8B3-4600-A25A-4FA95EE91337}
{017DB255-0006-484F-A983-539E9D1F1661}

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by sudhanshutech** [comment]
do not merge this now

**Comment by amitamrutiya** [comment]
@sudhanshutech @SAHU-01 is this ready for merge?

**Comment by sudhanshutech** [comment]
no @amitamrutiya its not ready to merge, there is some work left on the back side of card to incorporate the styles of technologies and some other minute styles

**Comment by amitamrutiya** [comment]
@sudhanshutech one request could you please prioritize this and merge this so I can use those cards in the extension repo as well? I want to use this in the empty kanvas catalog modal.

**Review by amitamrutiya — COMMENTED** [review]
Can you also add this code? Some of the cards without flip functionality behave differently.

Additionally, your PR has a different position for the back side version, so could you please check that as well?

**Comment by leecalcote** [comment]
@amitamrutiya directly commit to this branch. Take it over.

**Comment by amitamrutiya** [comment]
I don't have permission to do that 😔 @leecalcote .

**Comment by amitamrutiya** [comment]
I am going to merge this PR and will create a new PR that have some changes on top of this.

**Comment by sudhanshutech** [comment]
Sounds good @amitamrutiya 👍

**Pull request merged**
