### PR TITLE
Fix the overview js

### PR DESCRIPTION
**Pull request by Parv-gugnani**
# In this i fixed the overview js.

## Issue
there were issue when i was compiling them so get the error that previous was imported two times
so i fixed it.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks, @Parv-gugnani 👍

**Comment by leecalcote** [comment]
🚨 Alert! Git Police! We couldn’t help but notice that one or more of your commits is missing a sign-off. _A what?_ A commit sign-off (your email address).\n\n
         To amend the commits in this PR with your signoff using the instructions provided in the DCO check. \n\n
         To configure your dev environment to automatically signoff on your commits in the future, see [these instructions](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin).

**Comment by leecalcote** [comment]
@Parv-gugnani be sure to have a look at the merge conflict.

**Comment by Parv-gugnani** [comment]
Sure sir i am trying

**Comment by sudhanshutech** [comment]
@Parv-gugnani are sure you are not rebasing the commits

**Comment by Parv-gugnani** [comment]
can you help me what to do please guide

**Comment by sudhanshutech** [comment]
create a new pr, close this one

**Comment by leecalcote** [comment]
@Parv-gugnani still trying here or have you tossed in the towel?

**Comment by sudhanshutech** [comment]
Due to no activity for a month lets close this. If assignee returns then can be reopened.

**Pull request closed without merging**
