### PR TITLE
Add Markdown Render Component and Styles

### PR DESCRIPTION
**Pull request by codeKraken19**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by aabidsofi19** [comment]
@sudhanshutech  if you would migrate the RenderMarkdown component here to use react-markdown with the required plugins and styling  , and then use it in your cloud pr for catalog

**Comment by sudhanshutech** [comment]
sounds good @aabidsofi19 , sure

**Comment by aabidsofi19** [comment]
@nebula-aac  there is some issue with out bundling ,  when we import the RenderMarkdown component in cloud , it give `Error: Must use import to load ES Module` for `rehype` and `react-markdown` . but the same component if defined in cloud works properly .

**Comment by leecalcote** [comment]
@dragon-slayer875 will you have a look?

**Comment by sudhanshutech** [comment]
i am looking,  we are going to use react markdown library as discussed. There is some import error coming while use the library through sistent in cloud. Since this package is EcmaScript Module so while bundling in sistent its having issues

**Comment by sudhanshutech** [comment]
@aabidsofi19 i have created separate pr here: https://github.com/layer5io/sistent/pull/610 if it looks good then we can close this

**Pull request closed without merging**
