### PR TITLE
Feat: Sistent logo

### LINKED ISSUE #103: Logo Needed for Sistent
#### Description

The **logo** is needed for **Sistent** which aligns with the current theme of the Organization.

Here are some resources which may help you with inspiration for the logo:
- [Sistent Repository](https://github.com/layer5io/sistent)
- [Figma](https://www.figma.com/files/team/972159062361165490/Layer5?fuid=985940838624039218)
- [Brand-Kit](https://layer5.io/company/brand)

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

### PR DESCRIPTION
**Pull request by ptdatta**
**Notes for Reviewers**
Logo for Sistent
sistent_colored
sistent_white

This PR fixes #103 

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by ptdatta** [comment]
@ritiksaxena124 now?

**Comment by Debaditya-Som** [comment]
@ptdatta I've been assigned with a issue regarding lack of visual depiction of the project description (#148 ). I just want to know whether this logo is the finalized logo of the project? Then it would help me work on the issue :)

**Comment by ptdatta** [comment]
> @ptdatta I've been assigned with a issue regarding lack of visual depiction of the project description (#148 ). I just want to know whether this logo is the finalized logo of the project? Then it would help me work on the issue :)

I think you should ask @leecalcote or @ritiksaxena124

**Comment by Debaditya-Som** [comment]
> > @ptdatta I've been assigned with a issue regarding lack of visual depiction of the project description (#148 ). I just want to know whether this logo is the finalized logo of the project? Then it would help me work on the issue :)
> 
> I think you should ask @leecalcote or @ritiksaxena124

Okay thanks

**Pull request merged**
