### PR TITLE
bugfix: Correct `components` and `svg` components

### PR DESCRIPTION
**Pull request by nebula-aac**
**Notes for Reviewers**

This PR is related to https://github.com/layer5io/sistent/issues/180

- Correct the `Tooltip` import path
- Correct the imports calling `@layer5/sistent-components` and import internally in the `sistent-components`
- Correct imports to call `@layer5/sistent-svg` instead of calling the relative paths.
- There is no `FormControlLabel` component, there is one now
- There's also no `MenuItem` component, there is one now also
- Export `CloseIcon` and `SearchIcon` in `svg`

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@sudhanshutech @aabidsofi19

**Review by aabidsofi19 — APPROVED** [review]
Looks great .

**Comment by aabidsofi19** [comment]
@nebula-aac  has that build bug now solved in this pr .

**Review by sudhanshutech — APPROVED** [review]

**Comment by sudhanshutech** [comment]
> @nebula-aac has that build bug now solved in this pr .

i guess that will solved here: https://github.com/layer5io/sistent/pull/174

**Pull request merged**
