### PR TITLE
Convert cloud catalog sort menu and search field to sistent

### PR DESCRIPTION
**Pull request by amitamrutiya**
**Notes for Reviewers**

image

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by amitamrutiya** [comment]
@aabidsofi19 @sudhanshutech Now this catalog search and sort is useful for the open catalog model functionality. could you please review?

**Comment by amitamrutiya** [comment]
Done @aabidsofi19

**Comment by aabidsofi19** [comment]
confilcts here ,  make it a bit more generic ( not specific to catolog )

**Comment by amitamrutiya** [comment]
@aabidsofi19 There is no need to create a sort by component for the catalog we can build them from the other sistent component. For the search one we already have `stylesearchbar` that we are not using anywhere so i added some styles to it so it looks like a cloud one so we can use it in other places.  

I hope it make sense to you.

**Pull request merged**
