### PR TITLE
[components] created `searchbar` and `tooltip`

### PR DESCRIPTION
**Pull request by nebula-aac**
**Notes for Reviewers**

This PR fixes https://github.com/layer5io/sistent/issues/72 and https://github.com/layer5io/sistent/issues/73

In Meshery UI and Meshery Cloud and any others that uses MUI, we have a reusable tooltip but we're duplicating work in this.

For the `search bar`, we have this done in Meshery UI but it is not a complete replica of the one from Meshery UI, but it does takes most of the basic properties of what we're using Meshery UI.

These two components are also being used in the Design System.

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by aabidsofi19** [comment]
@nebula-aac  we should rename the `meshery` folder . maybe `base` for components are to be customized and `core` for the components that are more or less completely  styled , also the component name (filename) should not contain the name of folder then.

**Comment by nebula-aac** [comment]
This has been updated to rename the directories and the names of the custom components @aabidsofi19

**Comment by nebula-aac** [comment]
@aabidsofi19 can you review here again?

**Review by aabidsofi19 — APPROVED** [review]
Looks great

**Pull request merged**
