### PR TITLE
feat: add missing stories

### LINKED ISSUE #60: [storybook] Create missing stories
#### Mockups

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

### PR DESCRIPTION
**Pull request by kunal70006**
**Notes for Reviewers**

This PR fixes #60 

**Components covered**

- [x] Accordion
- [x] Avatar
- [x] Backdrop
- [x] Badge
- [x] Box
- [x] ButtonGroup
- [x] Card
- [x] Select
- [x] Dialog

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@kunal70006 good stuff

**Comment by kunal70006** [comment]
I also converted all stories to ts just so we can get more controls and stuff

**Comment by kunal70006** [comment]
@nebula-aac you can review this one now, i'll update the description to add the list of components that i covered

**Comment by nebula-aac** [comment]
okay, ill provide my feedback

**Review by nebula-aac — CHANGES_REQUESTED** [review]
@kunal70006 

Here is my review.

Before you get started, update your forked branch to include the latest changes. I opened a PR to include the missing exports from Accordion.

1. **Add these packages to `design-system`**
```bash
    "@layer5/sistent-components": "*",
    "@layer5/sistent-svg": "*",
```

Once you have done this, you will be able to use the packages locally. If it is not does work right away, from the root workspace run `yarn build-all` in order to build the artifacts. Either way, you still need the two above added to `design-system` package.

2. **Add `tsconfig.json`**, since you're suggesting to change to `Typescript`, please make this change the same throughout the entire `design-system` repo. There are some files that have the `.jsx` extensions. You can review existing `Vite` templates that has these config.

Once you have made the above changes, I can review again.

**Comment by Ghat0tkach** [comment]
hey @kunal70006 
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by kunal70006** [comment]
hey @Ghat0tkach I think it's already added in the word doc, do I need to do anything else? Also, can you tell me how long the meeting actually lasts because I've a blocker around 6PM IST/7:30AM CST(i think) so I'm only available from 7-7:30 Central

**Comment by nebula-aac** [comment]
At this time, the design system isn't working for me. I'm creating another PR to convert the entire design system to Typescript from scratch.

**Comment by kunal70006** [comment]
what errors are you facing? do you want to discuss?

**Pull request closed without merging**
