### PR TITLE
chore(theme): add interfaces for tokens and add few token

### PR DESCRIPTION
**Pull request by aabidsofi19**
**Notes for Reviewers**

This PR fixes https://github.com/layer5io/sistent/issues/511

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by sudhanshutech** [comment]
@aabidsofi19 are you doing the same thing what i am doing, if that so should update other areas in this pr only as per your changes. Or you will be doing?

**Comment by aabidsofi19** [comment]
@sudhanshutech  yup , you can continue on this pr

**Comment by aabidsofi19** [comment]
first lets copy paste the tokens from figma intp the theme , then start using them in components

**Comment by sudhanshutech** [comment]
got it

**Comment by sudhanshutech** [comment]
@aabidsofi19 do i required any type of access to push in this branch?

**Comment by leecalcote** [comment]
This PR is addressing https://github.com/layer5io/sistent/issues/511

**Pull request closed without merging**
