### PR TITLE
[svg] / [design-system] - Update explicit types, and added `eslint` config to `svg`

### PR DESCRIPTION
**Pull request by nebula-aac**
**Notes for Reviewers**

This PR fixes #

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by aabidsofi19** [comment]
why did we change it to JSX.Element  (curious)

**Comment by nebula-aac** [comment]
The updates comes from `eslint` rule

Here is an example of error when you run `eslint`.

```bash
/workspaces/sistent/packages/components/src/base/Accordion/accordionsummary.tsx
  4:8  error  Missing return type on function  @typescript-eslint/explicit-function-return-type
```

To satisfy the rule, we can explicitly label `JSX.Element` which means each of the component is returning an `JSX.Element`

We can either turn this rule off to make it less explicit, and allow some flexibility in using the components, or leave this rule on, and make sure that each of the component is returning an `JSX.Element`. This will allow Typescript to perform better type checking and also allow everyone else who is contributing to know this this is a particular type.

I'm open to either way.

**Comment by nebula-aac** [comment]
@aabidsofi19 Can you review again and see if this can be merged in.

I have more that I want to add, and don't want to create multiple PRs and rebasing the PRs if I can avoid it.

**Comment by aabidsofi19** [comment]
@nebula-aac sorry ,  i forgot to review some of the prs  ..

**Comment by aabidsofi19** [comment]
@nebula-aac  i think the return type should be React.FC rather than JSX.Element , because it is a react component as it takes props

**Comment by leecalcote** [comment]
Merge conflicts cropped up...

**Comment by nebula-aac** [comment]
I'm creating a different PR, closing this one.

**Pull request closed without merging**
