### PR TITLE
[component] Tooltip Icon

### LINKED ISSUE #376: [components]: Create `TooltipIcon`
### Requirements:

Create a reusable `Tooltip` icon that takes in an `IconButton` that can expose a props to take in an SVG component.

---

**[Contributor Guide](https://docs.meshery.io/project/contributing)**

- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

### PR DESCRIPTION
**Pull request by sudhanshutech**
**Notes for Reviewers**

This PR fixes #376 

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by sudhanshutech** [comment]
oh okay got it, i made pr i thought it was required for that same quick

**Review by leecalcote — APPROVED** [review]
We're ok to move forward?

**Comment by leecalcote** [comment]
> I will make this tooltip as the tooltip we use for information across modals

@sudhanshutech you didn't answer @nebula-aac's question.

**Comment by sudhanshutech** [comment]
> > I will make this tooltip as the tooltip we use for information across modals
> 
> @sudhanshutech you didn't answer @nebula-aac's question.

yes, its done now

**Comment by leecalcote** [comment]
@sudhanshutech there are two different tooltips being used in Meshery UI. 

@iArchitSharma should have recently filed an issue on this that he can link here. Let's consolidate to the better looking of the two, which _should be_ the Sistent tooltip. Hopefully, this is the good-looking tip.

**Comment by iArchitSharma** [comment]
Link to issue - https://app.clickup.com/t/86cuqu3qm
@sudhanshutech

**Comment by sudhanshutech** [comment]
thanks @iArchitSharma i will take a look on the task

**Pull request merged**
